# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ztisnes <ztisnes@student.42.us.org>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/05/21 20:12:59 by ztisnes           #+#    #+#              #
#    Updated: 2018/05/21 22:58:27 by ztisnes          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

SPHINX_TAP = brew tap watsonbox/cmu-sphinx

BASE_INS = brew install --HEAD watsonbox/cmu-sphinx/cmu-sphinxbase

POCKET_INS = brew install --HEAD watsonbox/cmu-sphinx/cmu-pocketsphinx

sphinx:
	$(SPINX_TAP)
	$(BASE_INS)
	$(POCKET_INS)
